/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.Livro;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhonatan Santos
 */
public class Smenu_Cadastro_Livro extends javax.swing.JPanel {

    Livro livro = new Livro();
    DefaultTableModel model;

    public Smenu_Cadastro_Livro() {
        initComponents();
        atualizarListLivro();
    }

    public void atualizarListLivro() {
        try {
            model = (DefaultTableModel) jTableLivros.getModel();
            model.setNumRows(0);
            for (int i = 0; i < livro.getLivro().size(); i++) {
                String[] listLivro = livro.getLivro().get(i).split(";");
                model.addRow(listLivro);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, "Erro ao Atualizar Livros", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextTitulo = new javax.swing.JTextField();
        jTextEditora = new javax.swing.JTextField();
        jTextCodigo = new javax.swing.JTextField();
        jTextAutor = new javax.swing.JTextField();
        jTextEdicao = new javax.swing.JTextField();
        jTextAno = new javax.swing.JTextField();
        jTextPaginas = new javax.swing.JTextField();
        jTextQuantidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLivros = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(600, 350));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 80, 25));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 11, 80, 25));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Excluir");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 11, 80, 25));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Pesquisar");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 11, 85, 25));

        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 11, 180, 25));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Foto");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Capa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, 124));

        jTextTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Titulo do Livro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        add(jTextTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 372, -1));

        jTextEditora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextEditora.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Editora", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        add(jTextEditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 223, -1));

        jTextCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Codigo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        add(jTextCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 102, -1));

        jTextAutor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextAutor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Autor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        add(jTextAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 247, -1));

        jTextEdicao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextEdicao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Edição", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        add(jTextEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 84, -1));

        jTextAno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextAno.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ano", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        add(jTextAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 84, -1));

        jTextPaginas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextPaginas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Paginas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        add(jTextPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 71, -1));

        jTextQuantidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextQuantidade.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Quantidade", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        add(jTextQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 87, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTableLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Titulo", "Autor", "Editora"
            }
        ));
        jTableLivros.setEditingColumn(0);
        jTableLivros.setEditingRow(0);
        jScrollPane1.setViewportView(jTableLivros);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 580, 120));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Fazer Emprestimo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 317, 130, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Reservar");
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 317, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Cadastro_Livros livros = new Cadastro_Livros();
        livros.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            limpar();
            livro.setDados(jTextTitulo.getText(), jTextCodigo.getText(), jTextEditora.getText(),
                    jTextAutor.getText(), jTextEdicao.getText(), jTextAno.getText(), jTextPaginas.getText(),
                    jTextQuantidade.getText(), "Disponivel");
            livro.setLivro();
            limpar();
            atualizarListLivro();
        } catch (IOException ex) {
            Logger.getLogger(Smenu_Cadastro_Livro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public void limpar() {
        jTextTitulo.setText("");
        jTextCodigo.setText("");
        jTextEditora.setText("");
        jTextAutor.setText("");
        jTextEdicao.setText("");
        jTextAno.setText("");
        jTextPaginas.setText("");
        jTextQuantidade.setText("");
    }

    public void getLivros() throws Exception {
        model = (DefaultTableModel) jTableLivros.getModel();
        model.setNumRows(0);
        //for (int i = 0; i < Banco.get().lerLivro().size(); i++) {
        //  String[] listLivro = Banco.get().lerLivro().get(i).split(";");
        // model.addRow(listLivro);
        //  }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLivros;
    private javax.swing.JTextField jTextAno;
    private javax.swing.JTextField jTextAutor;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextEdicao;
    private javax.swing.JTextField jTextEditora;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextPaginas;
    private javax.swing.JTextField jTextQuantidade;
    private javax.swing.JTextField jTextTitulo;
    // End of variables declaration//GEN-END:variables
}
